a=set(input('Enter set a: ').split())
b=set(input('Enter set b: ').split())
print('Union: ', a.union(b))
print('Intersection: ', a.intersection(b))
print('Are a and b disjoint: ', a.isdisjoint(b))
print('Is a subset of b: ', a.issubset(b))
print('IS a superset of b: ', a.issuperset(b))